ACTION_UP = 'u'
ACTION_DOWN = 'd'
ACTION_LEFT = 'l'
ACTION_RIGHT = 'r'

MOVEMENT = {
  ACTION_UP: (0, -1),
  ACTION_DOWN: (0, 1),
  ACTION_LEFT: (-1, 0),
  ACTION_RIGHT: (1, 0)
}

ALL_ACTIONS = [ACTION_UP, ACTION_RIGHT, ACTION_DOWN, ACTION_LEFT]
ALL_MOTIONS = [MOVEMENT[act] for act in ALL_ACTIONS]
